"""member endorsements

Revision ID: 852ff7a9b2a6
Revises: 65d76bc7fce0
Create Date: 2023-05-19 14:03:11.735473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852ff7a9b2a6'
down_revision = '65d76bc7fce0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endorsements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endorsements_id'), 'endorsements', ['id'], unique=False)
    op.create_table('members_endorsements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('endorsement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['endorsement_id'], ['endorsements.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_endorsements_id'), 'members_endorsements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_endorsements_id'), table_name='members_endorsements')
    op.drop_table('members_endorsements')
    op.drop_index(op.f('ix_endorsements_id'), table_name='endorsements')
    op.drop_table('endorsements')
    # ### end Alembic commands ###
