repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: no-commit-to-branch
        args: [--branch, development, --branch, master]
    -   id: check-merge-conflict
    -   id: debug-statements
        language_version: python3.10
    -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.1.3
    hooks:
    -   id: python-safety-dependencies-check
        stages: [manual]
-   repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
    -   id: bandit
        stages: [manual]
-   repo: https://github.com/twu/skjold
    rev: v0.1.5
    hooks:
    - id: skjold
      name: "skjold: Auditing dependencies for known vulnerabilities."
      entry: skjold audit
      args: [-s, gemnasium, -s, pyup]
      require_serial: true
      language: python
      language_version: python3.10
      files: ^(requirements.*\.txt)$
      stages: [manual]
-   repo: https://github.com/hakancelik96/unimport
    rev: 0.2.7
    hooks:
    - id: unimport
      args: [-r, --include-star-import]
      files: "\\.(py)$"
      exclude: (__init__.py)
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        language_version: python3.10
#-   repo: local
#    hooks:
#      - id: pytest
#        name: pytest
#        stages: [ push ]
#        entry: venv/bin/python -m coverage run -m pytest
#        language: script
#        verbose: true
#        pass_filenames: false
#        always_run: true
