"""First migration

Revision ID: 02afab93d221
Revises: 
Create Date: 2023-05-21 09:35:06.569214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02afab93d221'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_before_solo_student', sa.Boolean(), nullable=True),
    sa.Column('is_solo_student', sa.Boolean(), nullable=True),
    sa.Column('is_private_pilot', sa.Boolean(), nullable=True),
    sa.Column('is_cfi', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_id'), 'members', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_id'), table_name='members')
    op.drop_table('members')
    # ### end Alembic commands ###
