"""syllabuses

Revision ID: 147f1ce954f2
Revises: 3417a70b3411
Create Date: 2023-06-02 18:04:17.066695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147f1ce954f2'
down_revision = '3417a70b3411'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('syllabuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syllabuses_id'), 'syllabuses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_syllabuses_id'), table_name='syllabuses')
    op.drop_table('syllabuses')
    # ### end Alembic commands ###
