"""syllabus_items

Revision ID: 1cfb02c106f2
Revises: bea6ebd3d405
Create Date: 2023-06-03 11:22:13.277142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1cfb02c106f2"
down_revision = "bea6ebd3d405"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "syllabus_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("syllabus_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["syllabus_id"],
            ["syllabuses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint(
            "syllabus_id",
            "name",
            name="syllabus_item_syllabus_id_name_unique_constraint",
        ),
    )
    op.create_index(
        op.f("ix_syllabus_items_id"), "syllabus_items", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_syllabus_items_id"), table_name="syllabus_items")
    op.drop_table("syllabus_items")
    # ### end Alembic commands ###
