"""document type model

Revision ID: 26d95ce21125
Revises: c0d9279a8600
Create Date: 2023-06-02 23:08:47.580238

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26d95ce21125'
down_revision = 'c0d9279a8600'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_documents', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_documents', sa.Column('type', postgresql.ENUM('STUDENT_LICENSE', 'MEDICAL', 'MEMBERSHIP_AGREEMENT', name='memberdocumenttype'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
