"""First migration

Revision ID: 304cc2703d0d
Revises: 
Create Date: 2023-05-19 16:17:08.393666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304cc2703d0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endorsements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endorsements_id'), 'endorsements', ['id'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_id'), 'members', ['id'], unique=False)
    op.create_table('members_endorsements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('endorsement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['endorsement_id'], ['endorsements.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_endorsements_id'), 'members_endorsements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_endorsements_id'), table_name='members_endorsements')
    op.drop_table('members_endorsements')
    op.drop_index(op.f('ix_members_id'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_endorsements_id'), table_name='endorsements')
    op.drop_table('endorsements')
    # ### end Alembic commands ###
