"""instruction plans

Revision ID: 3417a70b3411
Revises: 9d0296cb8292
Create Date: 2023-06-02 17:40:05.840291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3417a70b3411'
down_revision = '9d0296cb8292'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruction_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruction_plans_id'), 'instruction_plans', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instruction_plans_id'), table_name='instruction_plans')
    op.drop_table('instruction_plans')
    # ### end Alembic commands ###
