"""instruction plan syllabuses

Revision ID: 6155d117114b
Revises: 147f1ce954f2
Create Date: 2023-06-02 19:17:28.947938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6155d117114b"
down_revision = "147f1ce954f2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instruction_plan_syllabuses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instruction_plan_id", sa.Integer(), nullable=True),
        sa.Column("syllabus_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["instruction_plan_id"],
            ["instruction_plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["syllabus_id"],
            ["syllabuses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "instruction_plan_id",
            "syllabus_id",
            name="instruction_plan_syllabus_instruction_plan_id_syllabus_id_uc",
        ),
    )
    op.create_index(
        op.f("ix_instruction_plan_syllabuses_id"),
        "instruction_plan_syllabuses",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_instruction_plan_syllabuses_id"),
        table_name="instruction_plan_syllabuses",
    )
    op.drop_table("instruction_plan_syllabuses")
    # ### end Alembic commands ###
