"""flights and demonstrations

Revision ID: 6371b513d389
Revises: fc39501f88a0
Create Date: 2023-06-07 17:42:43.784004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6371b513d389'
down_revision = 'fc39501f88a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('instructor_id', sa.Integer(), nullable=True),
    sa.Column('solo', sa.Boolean(), nullable=True),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flights_id'), 'flights', ['id'], unique=False)
    op.create_table('demonstrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('syllabus_item_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('sufficient', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['syllabus_item_id'], ['syllabus_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demonstrations_id'), 'demonstrations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_demonstrations_id'), table_name='demonstrations')
    op.drop_table('demonstrations')
    op.drop_index(op.f('ix_flights_id'), table_name='flights')
    op.drop_table('flights')
    # ### end Alembic commands ###
