"""document type model

Revision ID: a88444a166c9
Revises: c0d9279a8600
Create Date: 2023-06-02 23:17:16.751031

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a88444a166c9'
down_revision = 'c0d9279a8600'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_document_types_id'), 'document_types', ['id'], unique=False)
    op.add_column('member_documents', sa.Column('type_id', sa.Integer(), nullable=True))
    op.create_foreign_key('member_documents_type_id_fkey', 'member_documents', 'document_types', ['type_id'], ['id'])
    op.drop_column('member_documents', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_documents', sa.Column('type', postgresql.ENUM('STUDENT_LICENSE', 'MEDICAL', 'MEMBERSHIP_AGREEMENT', name='memberdocumenttype'), autoincrement=False, nullable=False))
    op.drop_constraint('member_documents_type_id_fkey', 'member_documents', type_='foreignkey')
    op.drop_column('member_documents', 'type_id')
    op.drop_index(op.f('ix_document_types_id'), table_name='document_types')
    op.drop_table('document_types')
    # ### end Alembic commands ###
