"""adds unique constraints

Revision ID: c0d9279a8600
Revises: 021774e2806f
Create Date: 2023-06-02 23:01:22.309934

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "c0d9279a8600"
down_revision = "021774e2806f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("courses_name_key", "courses", ["name"])
    op.create_unique_constraint("syllabuses_name_key", "syllabuses", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("syllabuses_name_key", "syllabuses", type_="unique")
    op.drop_constraint("courses_name_key", "courses", type_="unique")
    # ### end Alembic commands ###
