"""

Revision ID: dc5a79c5296a
Revises: a9aa2ab7c3cd
Create Date: 2023-06-01 22:22:14.037652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc5a79c5296a'
down_revision = 'a9aa2ab7c3cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('STUDENT_LICENSE', 'MEDICAL', 'MEMBERSHIP_AGREEMENT', name='memberdocumenttype'), nullable=False),
    sa.Column('expiration_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_documents_id'), 'member_documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_documents_id'), table_name='member_documents')
    op.drop_table('member_documents')
    # ### end Alembic commands ###
