"""syllabus item name is not unique

Revision ID: fc39501f88a0
Revises: 1cfb02c106f2
Create Date: 2023-06-03 12:01:55.113109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc39501f88a0'
down_revision = '1cfb02c106f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('syllabus_items_name_key', 'syllabus_items', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('syllabus_items_name_key', 'syllabus_items', ['name'])
    # ### end Alembic commands ###
